# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Required by RNFirebase
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Firestore';


target 'testWork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testWork

  target 'testWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


