export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const SET_CURRENT_FILM_ID = 'SET_CURRENT_FILM_ID';
export const FETCHING_COMMENTS_FAIL = 'FETCHING_COMMENTS_FAIL';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';


